[versions]
kotlin = "2.1.20"
kotest = "5.9.1"

[libraries]
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertations = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-data-driven = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version = "1.14.2" }
functional-interfaces = { module = "dev.nextftc:functional-interfaces", version = "1.0.1" }

[bundles]
kotest = ["kotest-runner", "kotest-assertations", "kotest-property", "kotest-data-driven"]

[plugins]
deployer = { id = "io.deepmedia.tools.deployer", version = "0.18.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }